<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.github.valtoni</groupId>
    <artifactId>javahistory</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.release>12</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.mainclass>org.github.valtoni.matrix.facilities.Main</project.mainclass>
        <project.cdnlist>${project.build.directory}${file.separator}classes.lst</project.cdnlist>
        <project.cdnfile>${project.build.directory}${file.separator}classes.jsa</project.cdnfile>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>5.11.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>module-facilities</module>
        <module>module-hovercraft</module>
        <module>module-matrix</module>
        <module>module-reality</module>
    </modules>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>3.5.0</version>
                    <configuration>
                        <executable>java</executable>
                        <arguments>
                            <argument>-XX:SharedArchiveFile=${project.cdnfile}</argument>
                            <argument>-cp</argument>
                            <classpath/>
                            <argument>${project.mainclass}</argument>
                        </arguments>
                    </configuration>
                    <executions>
                        <execution>
                            <id>cdn-generate-list</id>
                            <phase>process-classes</phase>
                            <goals>
                                <goal>exec</goal>
                            </goals>
                            <configuration>
                                <successCodes>0,1</successCodes>
                                <executable>java</executable>
                                <arguments>-XX:DumpLoadedClassList=${project.cdnlist}" -cp "${project.build.outputDirectory}</arguments>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>